"""ML-only interfaces for Partitura's Ruby-owned composition workflow."""

from generation.composition.benchmark import (
    AblationSpec,
    BenchmarkCase,
    BenchmarkCell,
    BenchmarkError,
    BenchmarkManifest,
    FrozenInput,
    StrategySpec,
)
from generation.composition.interfaces import (
    LearnedCompositionProvider,
    LearnedCritic,
    LearnedPolicy,
    LearnedProposer,
)
from generation.composition.critic_learning import (
    CriticCorpusIndex,
    CriticCorpusPreparer,
    CriticLearningError,
    CriticLearningSpec,
    OpaquePairFeatureExtractor,
    PairwiseCritic,
    PairwiseCriticTrainer,
    PreparedCriticCorpus,
    build_critic_corpus_index,
    verify_critic_artifacts,
)
from generation.composition.annotation_dataset import (
    AnnotationDataset,
    AnnotationDatasetBuilder,
    AnnotationDatasetError,
    AnnotationDatasetSpec,
    AnnotationObservation,
    AnnotationTargetSpec,
    TrainingExample,
)
from generation.composition.observation_dataset import (
    ObservationDataset,
    ObservationDatasetBuilder,
    ObservationDatasetError,
    ObservationDatasetSpec,
    ScoreObservation,
)
from generation.composition.evidence import (
    CompositionDataset,
    EvidenceError,
    HumanPreferenceRecord,
    PairwiseExample,
    PairwiseReviewRecord,
    TrajectoryRecord,
)
from generation.composition.evaluation import (
    ComparisonCell,
    EvaluationLab,
    EvaluationReport,
    ScorePreferenceRecord,
    ScoreReviewRecord,
)
from generation.composition.evaluation_run import EvaluationRun, RunEffort
from generation.composition.protocol import (
    ORIGINAL_CANDIDATE_ID,
    SCHEMA_VERSION,
    CandidateProposal,
    LearnedCriticResult,
    ProposalRequest,
    ProposalResponse,
    ProtocolError,
    SelectionRequest,
    SelectionResponse,
)
from generation.composition.representation_baselines import (
    RepresentationBaselineRunner,
)
from generation.composition.score_span_encoder import (
    PreparedScoreSpanDataset,
    ScoreSpanDatasetPreparer,
    ScoreSpanEncoder,
    ScoreSpanEncoderError,
    ScoreSpanEncoderSpec,
    ScoreSpanEncoderTrainer,
    verify_encoder_artifacts,
)
from generation.composition.structural_context import (
    StructuralContextError,
    StructuralContextSpec,
    StructuralSeamCritic,
    StructuralSeamScorer,
    StructuralSeamSignal,
)

__all__ = [
    "AblationSpec",
    "AnnotationDataset",
    "AnnotationDatasetBuilder",
    "AnnotationDatasetError",
    "AnnotationDatasetSpec",
    "AnnotationObservation",
    "AnnotationTargetSpec",
    "BenchmarkCase",
    "BenchmarkCell",
    "BenchmarkError",
    "BenchmarkManifest",
    "CandidateProposal",
    "CompositionDataset",
    "CriticCorpusIndex",
    "CriticCorpusPreparer",
    "CriticLearningError",
    "CriticLearningSpec",
    "build_critic_corpus_index",
    "EvidenceError",
    "EvaluationLab",
    "EvaluationReport",
    "EvaluationRun",
    "FrozenInput",
    "HumanPreferenceRecord",
    "LearnedCompositionProvider",
    "LearnedCritic",
    "LearnedCriticResult",
    "LearnedPolicy",
    "LearnedProposer",
    "ORIGINAL_CANDIDATE_ID",
    "ObservationDataset",
    "ObservationDatasetBuilder",
    "ObservationDatasetError",
    "ObservationDatasetSpec",
    "OpaquePairFeatureExtractor",
    "PairwiseExample",
    "PairwiseCritic",
    "PairwiseCriticTrainer",
    "PairwiseReviewRecord",
    "ProposalRequest",
    "ProposalResponse",
    "ProtocolError",
    "RepresentationBaselineRunner",
    "PreparedScoreSpanDataset",
    "PreparedCriticCorpus",
    "SCHEMA_VERSION",
    "RunEffort",
    "ScorePreferenceRecord",
    "ScoreObservation",
    "ScoreReviewRecord",
    "ScoreSpanDatasetPreparer",
    "ScoreSpanEncoder",
    "ScoreSpanEncoderError",
    "ScoreSpanEncoderSpec",
    "ScoreSpanEncoderTrainer",
    "SelectionRequest",
    "SelectionResponse",
    "TrajectoryRecord",
    "TrainingExample",
    "StrategySpec",
    "StructuralContextError",
    "StructuralContextSpec",
    "StructuralSeamCritic",
    "StructuralSeamScorer",
    "StructuralSeamSignal",
    "ComparisonCell",
    "verify_encoder_artifacts",
    "verify_critic_artifacts",
]
